### ISSUE TITLE
The website of Rotations Graph Averaging package is not found.

### ISSUE THREAD

**Issue by zhuohoudeputao** [wilsonkl/SfM_Init#12]
How can I get this package in another way? I'm studying your work, could you please help me?

**Comment by zhuohoudeputao** [comment]
Thanks!!! I'll try it now!

**Comment by zhuohoudeputao** [comment]
The new RGA website is available. It seems that the website of datasets should also be updated. Maybe it's this: https://research.cs.cornell.edu/1dsfm/

**Comment by wilsonkl** [comment]
Ah! Good catch. I've made those updates to the readme as well. Thanks!
