### ISSUE TITLE
Question regarding EGs.txt

### ISSUE THREAD

**Issue by sunghoon031** [wilsonkl/SfM_Init#16]
Hi. I have another question regarding the dataset you shared in https://research.cs.cornell.edu/1dsfm/.

Could you tell me how you computed the relative pose in EGs.txt? 

If you used an existing method for this, could you tell me what method I should refer to?

Thanks!

**Comment by wilsonkl** [comment]
We used the pipeline that's best described in the "Building Rome in a Day" paper. It was essentially the in-house version of Bunder, which doesn't differ that much from the public code. I do remember there there being a vocab-tree bag-of-words prematching stage that might not be in public Bundler. I think it used 40 nearest neighbor images.

**Comment by sunghoon031** [comment]
I see. Thanks!
