### ISSUE TITLE
The website of Rotations Graph Averaging package is not found, again

### ISSUE THREAD

**Issue by mimichu** [wilsonkl/SfM_Init#18]
Hi there, the provided link to the project page of Chatterjee and Govindu's rotations averaging code is not found again, I realize this have been updated in issue [#12](https://github.com/wilsonkl/SfM_Init/issues/12) in 2020 to https://ee.iisc.ac.in/labs/cvl/research/rotaveraging/, but looks like the page moved again! Would really appreciate it if it could be updated to the correct one! Thanks a lot!!

**Comment by wilsonkl** [comment]
Hi mimichu,
I wrote to Venu Govindu. His server is temporarily down. For now he gave me permission to distribute a copy of the rotsolver code. You'll find a new link in the README as before. 
-Kyle
