### ISSUE TITLE
Kind request for clarification on the final file "trans_problem_solution.txt"

### ISSUE THREAD

**Issue by alvaro562003** [wilsonkl/SfM_Init#6]
Hello Kyle,

Thank you for sharing this code.

This is not an issue at all but a kind request for a clarification. I hope you will have time to answer. 

I launched Sfm_init on "windows 10" and i now try to get confidence in the usage and the final result. 

I am using 3 camera connected like that: 0-1, 0-2, 1-2. 
The app generates 6 random numbers then used them to get 6 tracks and then extract the tracks' cameras. 

In my case, "orig_trans_problem.txt". containt 21 lines ( 6*3 + the 3 initials (0,1,2) ). 
Still in my case, the "1Dsfm_problem.txt" is identical to "orig_trans_problem.txt".

After complete execution, in "trans_problem_solution.txt" there is 9 lines left.  
I assume the 3 first represents the camera (0,1,2) and the 6 last represents the "camera-to-edge".

So my questions are : 
The 3 first lines represents the "cam-to-cam" relative translation and i can discard the 6 lasts. Right ?
Could i generate this assumption if i have N "cam-to-cam" relative translation and keep only the N first lines ?

The enclosure is the files for this case.
[MotionAveraging.zip](https://github.com/wilsonkl/SfM_Init/files/696314/MotionAveraging.zip)

**Comment by wilsonkl** [comment]
Hello Alvaro,

Thanks for your interest!

The cameras are indexed 0, 1, 2 as you see in the EGs.txt file. If the
problem is augmented with tracks (this is optional), then the tracks will
be assigned indices 3, 4, 5, ...

Usually I only care about the camera positions, and not the track
positions. In that case, I would keep the first three lines of the solution
file and discard the rest.

Suppose there are N cameras and M camera-to-camera relative translations.
Then the first N lines of the solutions file are camera positions, and the
first M lines of the problem file are the ones that have to do with the
camera-to-camera constraints. The rest of the files have to do with point
positions and camera-to-point constraints, respectively.

Hopefully this helps! If not, I'm quite happy to field more questions.

-Kyle

**Comment by alvaro562003** [comment]
Thank you very much that's crystal clear

**Comment by alvaro562003** [comment]
Hello KyleI downloaded this afternoon (paris time) the dataset mentioned in the poster "Robust Global Translations with 1DSfM "
The source is http://landmark.cs.cornell.edu/projects/1dsfm/images.Montreal_Notre_Dame.tarBut there are 2999 photos some of them are personal like this one
But there are 2999 photos some of them are personal like this one.Sure they are interesting but i was only interested by "Notre Dame" :-)Very Best Regards


 

      De : Kyle Wilson <notifications@github.com>
 À : wilsonkl/SfM_Init <SfM_Init@noreply.github.com> 
Cc : alvaro562003 <alvaro562003@yahoo.fr>; Author <author@noreply.github.com>
 Envoyé le : Vendredi 13 janvier 2017 3h50
 Objet : Re: [wilsonkl/SfM_Init] Kind request for clarification on the final file "trans_problem_solution.txt" (#6)
   
Hello Alvaro,

Thanks for your interest!

The cameras are indexed 0, 1, 2 as you see in the EGs.txt file. If the
problem is augmented with tracks (this is optional), then the tracks will
be assigned indices 3, 4, 5, ...

Usually I only care about the camera positions, and not the track
positions. In that case, I would keep the first three lines of the solution
file and discard the rest.

Suppose there are N cameras and M camera-to-camera relative translations.
Then the first N lines of the solutions file are camera positions, and the
first M lines of the problem file are the ones that have to do with the
camera-to-camera constraints. The rest of the files have to do with point
positions and camera-to-point constraints, respectively.

Hopefully this helps! If not, I'm quite happy to field more questions.

-Kyle

**Comment by wilsonkl** [comment]
Hi Alvaro,

The images were collected automatically, so they reflect some of the
messiness of real-world data. I can't see the particular photo that you
mention (there's no attachment, and the link doesn't work). If you only use
the images that were reconstructed in the bundle.out file, that should
filter things down to images that actually show the cathedral. Also, note
that this dataset is the Notre Dame Cathedral in Montreal, Canada, not the
one in Paris. If you want the Paris Notre Dame, that dataset is distributed
with bundler.
