### ISSUE TITLE
What is Sfm_init coordinate system ?

### ISSUE THREAD

**Issue by alvaro562003** [wilsonkl/SfM_Init#7]
Hello Kyle,

This is not an issue, i need a clarification on the coordinates system. 
As i am using Matlab and sift. I have to be sure on the coordinate system Sfm_Init is using.
So, what is Sfm_init coordinate system ?

Thank you very much again

For info :
Matlab coordinate system
Left corner : (1,1)
x axis pointing right.
y axis pointing downward.
[Height,Width]= size(readImage1); 

Vleaft sift coordinate system
Left corner: (0,0)
x axis pointing right.
y axis pointing downward.
source: http://www.vlfeat.org/overview/sift.html

ASIFT coordinate system
Left corner : (0,0)
x axis pointing right.
y axis pointing downward.
source: https://github.com/kif/imageAlignment/tree/master/asift

Bundler
lower-left corner (-w/2, -h/2)
the top-right corner (w/2, h/2) 
origin is the center of the image
x axis pointing right.
y axis pointing upward.
source: http://www.cs.cornell.edu/~snavely/bundler/bundler-v0.3-manual.html

**Comment by wilsonkl** [comment]
You mean the coordinate system for the coords.txt file? From the
documentation: "The coordinates <x> and <y> are in a coordinate system from
SIFT: the center of the upper left pixel is (1,1), +x points right, and +y
points down."

**Comment by alvaro562003** [comment]
Thank you
