### ISSUE TITLE
aberations in trans_problem_solution.txt

### ISSUE THREAD

**Issue by alvaro562003** [wilsonkl/SfM_Init#8]
Hello Kyle,

I am still integrating SFM_init in a classic matlab SFM project.

Sometimes in the file trans_problem_solution.txt  there are some aberations.  For example at line 21 below
20 -0.133264708712 0.992133578918 1.66608261415
21 -368554.531735 103353.696908 90712.47405
22 0.161763972331 -0.10153434714 0.122690909483

All other files "seems" good.

Do you have ever encountered this type of issue ?
And What should i do to correct this error ? (a subtle file format rule not respected  ?)

Thank you for your  help

[MotionAveraging.zip](https://github.com/wilsonkl/SfM_Init/files/723634/MotionAveraging.zip)

**Comment by wilsonkl** [comment]
Hi Alvaro,

Can you explain the problem in more detail? This looks like valid
formatting to me. Sometimes parts of translations problems are
ill-conditioned. Small noise can result in point locations that are very
far away from the rest of the model. That may well me the correct solution,
or something close to it.

**Comment by alvaro562003** [comment]
Hello Kylen
Indeed there were noise in my data.
After correction there were no more abberations.
Thank you for having share your experience.

By the way, what is the minimum images needed to use SFM_init ?

**Comment by wilsonkl** [comment]
A problem could be well-posed with as few as three images, if they were not
co-linear. With using scene points, the code could run with just two
images. I'm not sure that this would be useful for anything, but it is
definitely the lower bound.
